
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const RESET_ERROR = "RESET_ERROR";
export const SET_DATABASE = "SET_DATABASE";
export const CLEAR_DATABASE = "CLEAR_DATABASE";
export const DELETE_CONNECTION = "DELETE_CONNECTION";
export const SET_ACTIVE_TABLE = "SET_ACTIVE_TABLE";
export const SAVE_TABLE_STATE = "SAVE_TABLE_STATE";
export const SET_STEREOTYPES = "SET_STEREOTYPES";